### ISSUE TITLE
Package does not contain a manifest

### ISSUE THREAD

**Issue by kschepperly** [ITLec/ITLec.XrmToolBox.FormXmlManager#6]
Hi Mohamed,
I am having an issue with the FormXmlManager Plugin that you released on the XrmToolBox Plugins Store today. When I open the Plugins Store get an error "Package does not contain a manifest". I managed to trace it back to your specific plugin, version 1.2018.5.14. 

************** Exception Text **************
System.InvalidOperationException: Package does not contain a manifest.
   at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at NuGet.DataServicePackage.EnsurePackage(IPackageCacheRepository cacheRepository)
   at NuGet.DataServicePackage.get_FrameworkAssemblies()
   at NuGet.PackageExtensions.HasProjectContent(IPackage package)
   at NuGet.PackageWalker.GetPackageTarget(IPackage package)
   at NuGet.PackageWalker.GetPackageInfo(IPackage package)
   at NuGet.PackageWalker.ProcessPackageTarget(IPackage package)
   at NuGet.PackageWalker.Walk(IPackage package)
   at NuGet.InstallWalker.ResolveOperations(IPackage package)
   at NuGet.PackageManager.Execute(IPackage package, IPackageOperationResolver resolver)
   at NuGet.PackageManager.InstallPackage(IPackage package, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at XrmToolBox.PluginsStore.StoreFromPortal.PrepareInstallationPackages(List`1 pluginsToInstall, BackgroundWorker worker)
   at XrmToolBox.PluginsStore.StoreFormFromPortal.<tsbInstall_Click>b__18_5(Object sbw, DoWorkEventArgs evt)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by ITLec** [comment]
This issue has been solved, Kindly review the latest release.
